### ISSUE TITLE
PA Review: {Search for restaurants}

### ISSUE THREAD

**Issue by MasonChinkin** [MasonChinkin/availableFlatSurface#4]
- [ ] Backend: DB, model, controller, views
- [ ] Redux Loop: ajax, actions, reducer
- [ ] Presentational Components and Containers
- [ ] Styling
- [ ] Smooth, bug-free navigation
- [ ] Adequate and appropriate seeds

Note: My implementation of restaurant show page slice of state is not best practices. Will ping you tomorrow about it.

**Comment by ryan-mapa** [comment]
- [ ] search should have a no results found message

**Comment by MasonChinkin** [comment]
Added no results found
